version: '3'


volumes:
  nest-node-modules:
  react-node-modules:
  posgre-vol-dev:
  redis-vol-dev:

networks:
  docker-network:

services:
  postgres:
    container_name: posgre-dev
    image: postgres:latest
    env_file: env_files/posgre.dev.env
    volumes:
      - type: volume
        source: posgre-vol-dev
        target: /var/lib/postgresql/data
    networks:
      - docker-network
    restart: on-failure
    
  redis:
    container_name: redis-dev
    image: redis:latest
    volumes:
      - type: bind
        source: config/redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: redis-vol-dev
        target: /data
    networks:
      - docker-network
    restart: on-failure

  nest:
    container_name: nest-dev
    build:
      context: .
      dockerfile: Dockerfiles/Nest-dev-Dockerfile
    env_file: env_files/nest.dev.env
    ports:
      - target: 5555
        published: 5555
        host_ip: localhost
    volumes:
      - type: bind
        source: ${NESTDIR}
        target: /home/

      - type: volume
        source: nest-node-modules
        target: /home/node_modules/
    networks:
      - docker-network
    restart: on-failure

  react:
    container_name: react-dev
    build: 
      context: .
      dockerfile: Dockerfiles/React-dev-Dockerfile
    volumes:
      - type: bind
        source: ${REACTDIR}
        target: /home/

      - type: volume
        source: react-node-modules
        target: /home/node_modules/
    networks:
      - docker-network
    restart: on-failure

  nginx:
    container_name: nginx-dev
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        host_ip: localhost
      - target: 443
        published: 443
        host_ip: localhost
    volumes:
      - type: bind
        source: config/nginx-dev
        target: /etc/nginx/conf.d
    networks:
      - docker-network
    restart: on-failure


