version: '3'


volumes:
  nest-node-modules:
  react-node-modules:
  posgre-vol-prod:
  redis-vol-prod:

networks:
  docker-network:

services:
  postgres:
    container_name: posgre-prod
    image: postgres:latest
    env_file: env_files/posgre.dev.env
    volumes:
      - type: volume
        source: posgre-vol-prod
        target: /var/lib/postgresql/data
    networks:
      - docker-network
    restart: on-failure

  nest:
    container_name: nest-prod
    build:
      context: .
      dockerfile: Dockerfiles/Nest-prod-Dockerfile
    env_file: env_files/nest.dev.env
    ports:
      - 5555:5555 # for prisma studio
    volumes:
      - type: bind
        source: ${NESTDIR}
        target: /home/

      - type: volume
        source: nest-node-modules
        target: /home/node_modules/
    networks:
      - docker-network
    restart: on-failure

  react:
    container_name: react-prod
    build: 
      context: .
      dockerfile: Dockerfiles/React-prod-Dockerfile
    env_file: env_files/nest.prod.env
    volumes:
      - type: bind
        source: ${REACTDIR}
        target: /home/

      - type: volume
        source: react-node-modules
        target: /home/node_modules/

    networks:
      - docker-network
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        host_ip: localhost
      - target: 443
        published: 443
        host_ip: localhost
    volumes:
      - type: bind
        source: ${REACTDIR}/dist
        target: /usr/share/nginx/dist

      - type: bind
        source: config/nginx-prod
        target: /etc/nginx/conf.d
    networks:
      - docker-network
    restart: on-failure


